# Enterprise AI Configuration Example (YAML)

# LLM Configuration
llm:
  model: "gpt-4-1106-preview"
  base_url: "https://api.openai.com/v1"
  api_key: ""  # Set via environment variable OPENAI_API_KEY
  max_tokens: 4096
  temperature: 0.7
  api_type: "openai"
  api_version: ""

  # Example of model-specific override
  gpt4:
    model: "gpt-4-1106-preview"
    temperature: 0.5

  claude:
    model: "claude-3-opus-20240229"
    base_url: "https://api.anthropic.com/v1"
    api_key: ""  # Set via environment variable ANTHROPIC_API_KEY
    api_type: "anthropic"

# Sandbox Configuration
sandbox:
  use_sandbox: true
  image: "python:3.12-slim"
  work_dir: "/workspace"
  memory_limit: "512m"
  cpu_limit: 1.0
  timeout: 300
  network_enabled: false

# Browser Configuration
browser:
  headless: true
  disable_security: false
  extra_chromium_args: []
  max_content_length: 2000

# Search Configuration
search:
  engine: "Google"
  fallback_engines:
    - "DuckDuckGo"
    - "Bing"
  retry_delay: 60
  max_retries: 3

# Team Configuration
team:
  max_team_size: 10
  default_roles:
    - "manager"
    - "developer"
    - "researcher"
    - "analyst"

# Paths
# workspace_root: "/custom/path"  # Uncomment to override default
