name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install UV (Fast Python package manager)
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH  # Ensure uv is in PATH

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          uv venv .venv
          uv pip install --python .venv/bin/python -e "."
          uv pip install --python .venv/bin/python -e ".[dev]"

      - name: Run linters
        run: |
          uv run --python .venv/bin/python ruff check .
          uv run --python .venv/bin/python mypy --show-error-codes enterprise_ai/

      - name: Run tests
        run: uv run --python .venv/bin/python pytest -xvs tests/
